[package]
name = "sonic-migrate"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
colored = "2.0"
indicatif = "0.17"
thiserror = "1.0"
tempfile = "3.8"